# Generated by Django 4.1.4 on 2023-01-30 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('pid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=30)),
                ('price', models.FloatField(default=0.0)),
                ('net', models.IntegerField(default=0)),
                ('catagory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.catagory')),
            ],
        ),
    ]
