# Generated by Django 4.1.4 on 2023-02-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0003_alter_employee_birthdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product1',
            new_name='ProductM',
        ),
    ]
