# Generated by Django 4.1.4 on 2023-02-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0007_borrowing_contract_sme_payment_consideration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
