# Generated by Django 4.1.4 on 2023-02-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0008_alter_borrowing_borrow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ct_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
