# Generated by Django 4.1.4 on 2023-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0009_alter_contract_ct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ct_fine',
            field=models.CharField(default='', max_length=50),
        ),
    ]
