# Generated by Django 4.1.4 on 2023-02-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0010_alter_contract_ct_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pm_fine',
            field=models.CharField(default='', max_length=20),
        ),
    ]
