# Generated by Django 4.1.4 on 2023-02-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0011_alter_payment_pm_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pm_datepayment',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pm_file',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pm_fine',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pm_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
