# Generated by Django 4.1.4 on 2023-02-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0012_alter_payment_pm_datepayment_alter_payment_pm_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consideration',
            name='csd_date',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pm_datepayment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sme',
            name='sme_history',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sme',
            name='sme_regis',
            field=models.CharField(default='', max_length=10),
        ),
    ]
