# Generated by Django 4.1.4 on 2023-02-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0014_alter_payment_pm_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pm_file',
            field=models.FileField(default='', max_length=1000, upload_to=''),
        ),
    ]
