# Generated by Django 4.1.4 on 2023-02-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0015_alter_payment_pm_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pm_file',
            field=models.FileField(default='', upload_to='static/images'),
        ),
    ]
