# Generated by Django 4.1.4 on 2023-02-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0016_alter_payment_pm_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pm_file',
            field=models.CharField(default='', max_length=100),
        ),
    ]
