# Generated by Django 4.1.4 on 2023-02-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0017_alter_payment_pm_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='', max_length=400)),
                ('tel', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='12345678', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('eid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField(default=None)),
                ('position', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='12345678', max_length=255)),
            ],
        ),
    ]
