# Generated by Django 4.1.4 on 2023-02-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0018_customers_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme',
            name='cid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.customers'),
        ),
    ]
