# Generated by Django 4.1.4 on 2023-02-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0019_sme_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sme',
            name='cid',
        ),
        migrations.AddField(
            model_name='sme',
            name='customersid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.customers'),
        ),
    ]
