# Generated by Django 4.1.4 on 2023-02-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0020_remove_sme_cid_sme_customersid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sme',
            name='customersid',
        ),
        migrations.AddField(
            model_name='sme',
            name='customerid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
