# Generated by Django 4.1.4 on 2023-02-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0021_remove_sme_customersid_sme_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goodscategory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
