# Generated by Django 4.1.4 on 2023-02-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0023_alter_sme_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='customerid',
            field=models.CharField(default='', max_length=13),
        ),
    ]
