# Generated by Django 4.1.4 on 2023-02-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0025_customer_goodscategory_order_orderdetail_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sme',
            name='customerid',
        ),
        migrations.AddField(
            model_name='sme',
            name='cid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.customers'),
        ),
    ]
