# Generated by Django 4.1.4 on 2023-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0026_remove_sme_customerid_sme_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='cid',
            field=models.CharField(default='', max_length=13),
        ),
    ]
