# Generated by Django 4.1.4 on 2023-02-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0027_alter_sme_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='cid',
            field=models.ForeignKey(default=None, max_length=13, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.customers'),
        ),
    ]
