# Generated by Django 4.1.4 on 2023-02-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0028_alter_sme_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sme',
            old_name='cid',
            new_name='customer',
        ),
    ]
