# Generated by Django 4.1.4 on 2023-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0031_alter_borrowing_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_file',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
