# Generated by Django 4.1.4 on 2023-02-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0032_alter_borrowing_borrow_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_file',
            field=models.CharField(default='', max_length=100),
        ),
    ]
